### ISSUE TITLE
支持 AcFun 视频截图

### ISSUE THREAD

**Issue by GPBeta** [Dwscdv3/AdFunced-bilibili-capture#1]
~~为了更好地玩 ABC 梗~~ 希望可以加入对 AcFun 视频截图的支持。
A 站播放器做得比 B 站糟糕多了，特别是视频暂停会有 500ms 左右的延迟，手动预判截图难度十分大，如果能在 A 站加入逐帧步进的话就十分 Awesome 了（如果 A 站下一季还有我追的番的话（

**Comment by Dwscdv3** [comment]
好的。

不常用 AcFun，有什么需要特别注意的吗？例如像 bilibili 的番剧有特殊 path 之类的情况？

**Comment by Dwscdv3** [comment]
顺便一提，空格键是可以即时暂停的（虽然是 keyup 触发），可以在脚本更新之前暂时缓解这个问题（

**Comment by Dwscdv3** [comment]
坑 1：

A 站视频信息里的 FPS 实际上是实时渲染速率，而且只要不处于播放状态就是 0……

目前考虑持续轮询取最大值，并且 fallback 到 24。

**Comment by GPBeta** [comment]
我就知道很多坑，不然不会鼠标暂停都做不好

**Comment by Dwscdv3** [comment]
这个 issue 我先留着了，如果测试没问题的话请关一下（

**Comment by GPBeta** [comment]
怎么我刚测完就关了😂

**Comment by Dwscdv3** [comment]
> 怎么我刚测完就关了😂

😏微博上刷到了你发的截图，就顺便过来看看关没关（x
