### ISSUE TITLE
新番页面视频已失效

### ISSUE THREAD

**Issue by GPBeta** [Dwscdv3/AdFunced-bilibili-capture#2]
24 号开始无法在新番页面使用快捷键截图，普通视频暂无影响。

**Comment by Dwscdv3** [comment]
抱歉刚看到通知，明天修复。

另外，弹幕开关增强可能会移除并转移至个人自用脚本，因为其功能与此项目无关并导致了特定情况下弹幕无法显示的 bug。

**Comment by Dwscdv3** [comment]
似乎包含中文的 GitHub Issues 邮件都会被智障 Outlook 标记为不重要，不会收到推送。

**Comment by GPBeta** [comment]
没事，我甚至都不知道有那个功能（
这次 B 站番剧播放器升级，仅限番剧的播放器且部分用户会升级到 3.0.x beta。
不知道你那边能不能复现，我这边好几个脚本都受到影响。

**Comment by Dwscdv3** [comment]
我这里[番剧页面](https://www.bilibili.com/bangumi/play/ep164977)还是老样子。灰度测试？

倒是已知在“一起看”页面下无法正常工作。

**Comment by GPBeta** [comment]
![20210628153113](https://user-images.githubusercontent.com/13177262/123597429-ea3a2200-d825-11eb-8883-cd97dd133fdd.png)
估计你那边还是 2.x 的播放器了

**Comment by Dwscdv3** [comment]
确实还是 2.60.5 版本。

总之改成直接使用第一个 \<video\> 元素而不按 class 名查找了，希望能解决问题。

顺便放飞自我大改了一番（327++ 190--

1.0.0 changelog
**破坏性更新**
```
+ 现已支持所有网站（新增了默认行为，同时允许每个网站继承并 override 默认行为）
+ 在编码 GIF 时显示进度
+ 通过分析帧时间来检测视频帧率（需要 Chrome 83+，非标准特性）
+ 补上了自动更新地址
! 图片质量移动到设置面板，数字快捷键已移除
! 复制到剪贴板的快捷键更改为未选中文本时 Ctrl+C
- 移除了弹幕开关增强
* 代码已按照另一项目 popcorny 的设计模式完全重构
```

0.3.3 changelog
**未发布版本**
```
+ 在 GIF 录制中使用 pica 代替浏览器原生降采样以保证在所有平台上都有效果一致的高质量降采样（可能稍微影响性能）
```

**Comment by GPBeta** [comment]
快捷键 `s` 和 `c` 都不可用
```
userscript.html:920 Uncaught ReferenceError: bvid is not defined
    at Object.getId (userscript.html:920)
    at eval (userscript.html?:1004)
```
963 行还不停打印帧速 `console.log(this._highestFPS);`

**Comment by Dwscdv3** [comment]
> userscript.html:920 Uncaught ReferenceError: bvid is not defined

那可能是新版播放器移除了这几个 API…… 不知道还有没有什么替代

> 963 行还不停打印帧速 console.log(this._highestFPS);

大意了，忘了删（x

**Comment by Dwscdv3** [comment]
bvid 是我用来填充截图的文件名的，如果没了就只能从地址栏提取了

**Comment by GPBeta** [comment]
得找个办法让你用上 beta 播放器
